name: CI checks

on:
   pull_request: {}
   workflow_dispatch:
 
    
jobs:
   call-workflow:
    uses: studiographene/studiographene-nodejs-scans/.github/workflows/ci.yml@master 
    with:
      project_name: nextjs-boilerplate 
